openapi: '3.0.2'
info:
  title: PiEar REST API
  version: '1.0'
servers:
  - url: http://localhost:9090
paths:
  /channel-name:
    description: Get and set a channel name (Base64 encoded)
    get:
      description: Get channel count
      parameters: 
        - in: query
          name: id
          schema:
            type: integer
          required: false
          description: ID of the channel to get the name of
      responses:
        '200':
          description: Channel information. If id is not set, the channel count is returned.
          content:
            application/json:
              schema:
                type: object
    put:
      description: Set the channel name (Base64 encoded)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
      parameters: 
        - in: query
          name: name
          schema:
            type: string
          required: true
          description: new name of the channel
        - in: query
          name: id
          schema:
            type: integer
          required: true
          description: ID of the channel to get the name of
  /bpm:
    description: Get and set the bpm
    get:
      description: Get the current BPM
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
    put:
      description: Set the current BPM
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
      parameters:
        - in: query
          name: bpm
          schema:
            type: integer
          required: false
          description: new bpm
        - in: query
          name: bpmEnabled
          schema:
            type: boolean
          required: false
          description: new bpm
  /devices:
    description: Get the list of audio devices, and set the active one
    get:
      description: Get audio devices
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
    put:
      description: Set the active audio device
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
          description: index, as provided by the get
